/**
 * ChemSpace Secure Downloads Manager & Private Storage Service
 * Enforces strict user isolation: only files actually downloaded or generated by
 * the authenticated user appear here. Zero fake downloads.
 */

import { getCurrentUserUid } from './workspaceApi';
import { logActivity } from './activityStore';
import { API_URL } from './api';

const API_BASE = `${API_URL}/workspace/downloads`;

function getAuthHeader() {
  const token = localStorage.getItem('chemspace_token');
  if (!token) return {};
  return {
    Authorization: `Bearer ${token}`
  };
}

function getLocalPartitionKey() {
  const uid = getCurrentUserUid();
  return `chemspace_user_downloads_${uid || 'guest'}`;
}

/**
 * Record a real download event generated from any scientific module
 */
export async function recordDownload({
  filename,
  fileType = 'mol',
  sourceModule = 'ChemDraw',
  contentBlob = null,
  fileSize = null
}) {
  const uid = getCurrentUserUid();
  const token = localStorage.getItem('chemspace_token');

  const calculatedSize = fileSize || (contentBlob ? new Blob([contentBlob]).size : 0);
  const downloadId = `dl_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  const now = Date.now() / 1000;

  const itemRecord = {
    id: downloadId,
    fileName: filename,
    fileType,
    fileSize: calculatedSize,
    sourceModule,
    contentBlob: contentBlob || null,
    downloadStatus: 'completed',
    createdAt: now,
    date: new Date().toLocaleDateString(undefined, {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  };

  // 1. Save to local user partition
  saveLocalPartitionedDownload(itemRecord);

  // 2. Log to activity store
  logActivity(
    sourceModule,
    `Exported ${filename}`,
    `Type: ${fileType.toUpperCase()} • Size: ${formatBytes(calculatedSize)}`,
    'download',
    null,
    { downloadId, filename, fileType }
  );

  // 3. If authenticated, push to backend
  if (token && !token.startsWith('guest_')) {
    try {
      await fetch(API_BASE, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeader()
        },
        body: JSON.stringify({
          id: downloadId,
          filename,
          file_type: fileType,
          file_size: calculatedSize,
          source_module: sourceModule,
          content_blob: contentBlob ? String(contentBlob) : null
        })
      });
    } catch {
      // Local copy already saved
    }
  }

  return itemRecord;
}

/**
 * Fetch downloads strictly belonging to the current user
 */
export async function fetchUserDownloads({ search = '', sort = 'newest', limit = 50, offset = 0 } = {}) {
  const uid = getCurrentUserUid();
  const token = localStorage.getItem('chemspace_token');

  if (!token || token.startsWith('guest_')) {
    return fetchLocalPartitionedDownloads(search, sort);
  }

  try {
    const params = new URLSearchParams({
      search: search || '',
      sort: sort || 'newest',
      limit: String(limit),
      offset: String(offset)
    });

    const res = await fetch(`${API_BASE}?${params}`, {
      headers: {
        'Content-Type': 'application/json',
        ...getAuthHeader()
      }
    });

    if (res.ok) {
      const data = await res.json();
      return data;
    }
  } catch {
    // Fallback to local partition
  }

  return fetchLocalPartitionedDownloads(search, sort);
}

/**
 * Re-download a file from the user's past exports
 */
export function triggerFileDownload(downloadItem) {
  if (!downloadItem) return;

  const content = downloadItem.contentBlob || downloadItem.content;
  if (!content) {
    alert('File content is no longer cached in memory.');
    return;
  }

  const mimeMap = {
    mol: 'chemical/x-mdl-molfile',
    sdf: 'chemical/x-mdl-sdfile',
    pdb: 'chemical/x-pdb',
    xyz: 'chemical/x-xyz',
    cif: 'chemical/x-cif',
    csv: 'text/csv',
    json: 'application/json',
    txt: 'text/plain',
    py: 'text/x-python'
  };

  const ext = (downloadItem.fileType || downloadItem.fileName.split('.').pop() || 'txt').toLowerCase();
  const mime = mimeMap[ext] || 'application/octet-stream';

  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = downloadItem.fileName || `download.${ext}`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Delete a download record
 */
export async function deleteDownloadRecord(downloadId) {
  const token = localStorage.getItem('chemspace_token');
  deleteLocalPartitionedDownload(downloadId);

  if (token && !token.startsWith('guest_')) {
    try {
      await fetch(`${API_BASE}/${downloadId}`, {
        method: 'DELETE',
        headers: {
          ...getAuthHeader()
        }
      });
    } catch {}
  }
  return { status: 'success' };
}

/**
 * Clear all downloads for current user
 */
export async function clearDownloadsHistory() {
  const token = localStorage.getItem('chemspace_token');
  const key = getLocalPartitionKey();
  localStorage.removeItem(key);

  if (token && !token.startsWith('guest_')) {
    try {
      await fetch(API_BASE, {
        method: 'DELETE',
        headers: {
          ...getAuthHeader()
        }
      });
    } catch {}
  }
  return { status: 'success' };
}

// ----------------- LOCAL PARTITION HELPERS -----------------

function fetchLocalPartitionedDownloads(search = '', sort = 'newest') {
  try {
    const key = getLocalPartitionKey();
    const raw = localStorage.getItem(key);
    let items = raw ? JSON.parse(raw) : [];

    if (search) {
      const q = search.toLowerCase();
      items = items.filter(
        (i) =>
          (i.fileName && i.fileName.toLowerCase().includes(q)) ||
          (i.sourceModule && i.sourceModule.toLowerCase().includes(q)) ||
          (i.fileType && i.fileType.toLowerCase().includes(q))
      );
    }

    if (sort === 'oldest') {
      items.sort((a, b) => (a.createdAt || 0) - (b.createdAt || 0));
    } else {
      items.sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0));
    }

    return {
      status: 'success',
      items,
      total: items.length,
      limit: items.length,
      offset: 0
    };
  } catch {
    return { status: 'success', items: [], total: 0, limit: 0, offset: 0 };
  }
}

function saveLocalPartitionedDownload(item) {
  try {
    const key = getLocalPartitionKey();
    const raw = localStorage.getItem(key);
    let items = raw ? JSON.parse(raw) : [];
    items.unshift(item);
    localStorage.setItem(key, JSON.stringify(items.slice(0, 50)));
  } catch {}
}

function deleteLocalPartitionedDownload(id) {
  try {
    const key = getLocalPartitionKey();
    const raw = localStorage.getItem(key);
    if (!raw) return;
    let items = JSON.parse(raw);
    items = items.filter((i) => i.id !== id);
    localStorage.setItem(key, JSON.stringify(items));
  } catch {}
}

export function formatBytes(bytes, decimals = 1) {
  if (!bytes || bytes === 0) return '0 B';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
}
